select namefamily,shenasname,namepedar,kodmeli,
       tarikhtavalod,
       (select text from eform_define_sub_control where formid=176and controlid='jensiat' and value=jensiat) as jensiat,
telhamrah,
telsabet,
adress,
(select text from eform_define_sub_control where formid=176and controlid='nezamvazife' and value=nezamvazife) as
    nezamvazife,
                                               (select text from eform_define_sub_control where formid=176and controlid='tahol' and value=tahol) as tahol,
    post,
                                                                                              (select text from eform_define_sub_control where formid=176and controlid='mtahsili' and value=mtahsili) as mtahsili,
                                                                                                                                             (select text from eform_define_sub_control where formid=176and controlid='reshte' and value=reshte) as reshte,
    moadel1,
    uni1,
    sal1,
    madrakzaban1,
    madrakzaban2,
    onvanmadrak1,
    onvanmadrak2,
                                                                                                                                                                                            (select text from eform_define_sub_control where formid=176and controlid='khandan1' and value=khandan1) as khandan1,
                                                                                                                                                                                                                                           (select text from eform_define_sub_control where formid=176and controlid='khandan2' and value=khandan2) as khandan2,
                                                                                                                                                                                                                                                                                          (select text from eform_define_sub_control where formid=176and controlid='neveshtan1' and value=neveshtan1) as neveshtan1,
                                                                                                                                                                                                                                                                                                                                         (select text from eform_define_sub_control where formid=176and controlid='neveshtan2' and value=neveshtan2) as neveshtan2,
                                                                                                                                                                                                                                                                                                                                                                                        (select text from eform_define_sub_control where formid=176and controlid='mokaleme1' and value=mokaleme1) as mokaleme1,
                                                                                                                                                                                                                                                                                                                                                                                                                                       (select text from eform_define_sub_control where formid=176and controlid='mokaleme2' and value=mokaleme2) as mokaleme2,
    narmafzarha,
    maghaledakheli,
    maghalekhareji,
    elmitarviji,
    konferansi,
    kotob,
    tadris,
    mahaltadris,
    doreha,
    dastgah1,
    semat1,
    mardak1,
    tarikhd11,
    tarikhd1,
    dastgah2,
    semat2,
    mardak2,
    tarikhd2,
    tarikhd22,
    dastgah3,
    semat3,
    mardak3,
    tarikhd3,
    tarikhd33,
    dastgah4,
    semat4,
    mardak4,
    mardak3,
    tarikhd3,
    tarikhd33,
    dastgah4,
    semat4,
    mardak4,
    tarikhd4,
    tarikhd44,
    dastgah5,
    semat5,
    mardak5,
    tarikhd5,
    tarikhd55,
    dastgah6,
    semat6,
    mardak6,
    tarikhd6,
    tarikhd66,
    faaliat,
    shayestegi,
    barname,
    khalaghiat,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (select dbo.GetTextOfChkEform(chk1,176,'chk1')) as chk1,
    code,dl123
from EntesabEntekhab5 order by code desc
